-- Sahayak AI: run in Supabase SQL editor. Auth users live in auth.users.
create extension if not exists "pgcrypto";
create type public.eligibility_result as enum ('eligible','possibly_eligible','not_eligible','insufficient_information');
create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, full_name text, age smallint check(age between 0 and 130), gender text, state text, district text, occupation text, annual_income numeric(14,2) check(annual_income >= 0), social_category text, area_type text check(area_type in ('rural','urban')), disability_status text, family_details jsonb default '{}'::jsonb, updated_at timestamptz default now());
create table public.scheme_categories (id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null, description text);
create table public.schemes (id uuid primary key default gen_random_uuid(), name text not null, department text not null, summary text not null, objective text, benefits jsonb default '[]'::jsonb, beneficiaries text, coverage text default 'central', state text, application_mode text, application_url text, official_source_url text not null, important_conditions text, last_updated date, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.scheme_category_map (scheme_id uuid references public.schemes(id) on delete cascade, category_id uuid references public.scheme_categories(id) on delete cascade, primary key(scheme_id, category_id));
create table public.eligibility_rules (id uuid primary key default gen_random_uuid(), scheme_id uuid not null references public.schemes(id) on delete cascade, field text not null, operator text not null check(operator in ('equals','lte','gte','in')), value jsonb not null, label text, required boolean default true, display_order int default 0);
create table public.scheme_documents (id uuid primary key default gen_random_uuid(), scheme_id uuid not null references public.schemes(id) on delete cascade, name text not null, description text, required boolean default true, display_order int default 0);
create table public.saved_schemes (user_id uuid references auth.users(id) on delete cascade, scheme_id uuid references public.schemes(id) on delete cascade, saved_at timestamptz default now(), primary key(user_id, scheme_id));
create table public.eligibility_checks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, scheme_id uuid not null references public.schemes(id), result public.eligibility_result not null, score smallint check(score between 0 and 100), matched jsonb default '[]'::jsonb, unmatched jsonb default '[]'::jsonb, missing jsonb default '[]'::jsonb, explanation text, created_at timestamptz default now());
create table public.chat_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text, created_at timestamptz default now());
create table public.chat_messages (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.chat_sessions(id) on delete cascade, role text check(role in ('user','assistant','system')), content text not null, sources jsonb default '[]'::jsonb, created_at timestamptz default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, kind text not null, title text not null, body text, source_scheme_id uuid references public.schemes(id), read_at timestamptz, created_at timestamptz default now());
create table public.admins (user_id uuid primary key references auth.users(id) on delete cascade, role text not null default 'editor', created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.saved_schemes enable row level security; alter table public.eligibility_checks enable row level security; alter table public.chat_sessions enable row level security; alter table public.chat_messages enable row level security; alter table public.notifications enable row level security;
create policy "profile is private" on public.profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved is private" on public.saved_schemes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "checks are private" on public.eligibility_checks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sessions are private" on public.chat_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "messages via owned session" on public.chat_messages for all using (exists(select 1 from public.chat_sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy "notifications private" on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
-- Public clients can only read active scheme data; admin mutations should use a secure service role API.
alter table public.schemes enable row level security; create policy "read active schemes" on public.schemes for select using (active = true);